name       : budgie-desktop-branding
version    : '8'
release    : 23
source     :
    - https://github.com/solus-project/budgie-desktop-branding/releases/download/v9/budgie-desktop-branding-9.tar.xz : 68d1630c13fc865503df07fdc9c113ee68f8a3451aa04cb455d816599ee367ca
license    : GPL-2.0
summary    : Budgie Desktop Experience Configuration
component  : desktop.budgie
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
        - /usr/share/lightdm
rundeps    :
    - arc-gtk-theme
    - arc-icon-theme
    - breeze-cursor-theme
    - budgie-desktop
    - faba-icon-theme-mono
    - font-clear-sans-ttf
    - qtstyleplugins
    - solus-artwork
description: |
    Defaults for the Budgie Desktop
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
