name       : budgie-desktop-branding
version    : '22.1'
release    : 68
source     :
    - https://github.com/getsolus/budgie-desktop-branding/releases/download/v22.1/budgie-desktop-branding-v22.1.tar.xz : ce9b1dde4c51c7f4644b0cfd75fb16996cb00aeb40b1dbecc2ceb39e094cc40c
license    : GPL-2.0-only
summary    :
    - Budgie Desktop Experience Configuration
    - livecd : Budgie LiveCD-specific Configuration
description:
    - Defaults for the Budgie Desktop
    - livecd : Budgie LiveCD-specific Configuration
component  :
    - desktop.budgie
    - livecd : desktop.budgie
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/50_budgie_settings.gschema.override
        - /usr/share/lightdm/lightdm.conf.d/budgie_config.conf
replaces   :
    - budgie-desktop-branding-fortitude
    - budgie-desktop-branding-fortitude-plus
    - budgie-desktop-branding-material
rundeps    :
    - breeze-cursor-theme
    - budgie-backgrounds
    - budgie-desktop
    - font-clear-sans-ttf
    - materia-gtk-theme
    - materia-gtk-theme-dark
    - noto-sans-ttf
    - papirus-icon-theme
    - qtstyleplugins
    - solus-artwork
    - livecd :
        - budgie-desktop-branding
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
