name       : budgie-desktop-branding
version    : '16'
release    : 32
source     :
    - https://github.com/solus-project/budgie-desktop-branding/releases/download/v16/budgie-desktop-branding-16.tar.xz : ba6c015db22d61474047b34afa76f1e4c0edcc589deb6dff74b205a8b4b734c4
license    : GPL-2.0
summary    :
    - Budgie Desktop Experience Configuration
    - material : Material design inspired Budgie Desktop experience
component  : desktop.budgie
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
        - /usr/share/lightdm
    - material :
        - /usr/share/glib-2.0/schemas/20_budgie_material_settings.gschema.override
        - /usr/share/lightdm/lightdm-gtk-greeter.conf.d/20_budgie_material.conf
        - /usr/share/budgie-desktop/layouts/solus-material.layout
rundeps    :
    - breeze-cursor-theme
    - font-clear-sans-ttf
    - qtstyleplugins
    - solus-artwork
    - material :
        - budgie-desktop-branding
        - adapta-gtk-theme
        - papirus-icon-theme
        - noto-sans-ttf
        - font-roboto-ttf
description: |
    Defaults for the Budgie Desktop
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
