name       : budgie-desktop-branding
version    : 4
release    : 11
source     :
    - https://github.com/solus-project/budgie-desktop-branding/releases/download/v4/budgie-desktop-branding-4.tar.xz : c61279f945e661cbcff3461741f67ce711b68de59667fd61c64ba076e937790e
license    : GPL-2.0
summary    : Budgie Desktop Experience Configuration
component  : desktop.budgie
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
        - /usr/share/lightdm
rundeps    :
    - solus-artwork
    - breeze-snow-cursor-theme
    - font-clear-sans-ttf
    - arc-gtk-theme
    - faba-icon-theme-mono
    - arc-icon-theme
description: |
    Defaults for the Budgie Desktop
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
