name       : budgie-desktop-branding
version    : '18'
release    : 38
source     :
    - https://github.com/solus-project/budgie-desktop-branding/releases/download/v18/budgie-desktop-branding-18.tar.xz : d8c3542ae2a981ecc4902b679b53c7183b2c1901085751dba6731a79a72da128
license    : GPL-2.0-only
summary    :
    - Budgie Desktop Experience Configuration
    - material : Material design inspired Budgie Desktop experience
component  : desktop.budgie
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
        - /usr/share/lightdm
    - material :
        - /usr/share/glib-2.0/schemas/20_budgie_material_settings.gschema.override
        - /usr/share/lightdm/lightdm-gtk-greeter.conf.d/20_budgie_material.conf
        - /usr/share/budgie-desktop/layouts/solus-material.layout
rundeps    :
    - breeze-cursor-theme
    - font-clear-sans-ttf
    - qtstyleplugins
    - solus-artwork
    - material :
        - adapta-gtk-theme
        - budgie-desktop-branding
        - font-roboto-ttf
        - noto-sans-ttf
        - papirus-icon-theme
description: |
    Defaults for the Budgie Desktop
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
