name       : budgie-desktop-branding
version    : '17'
release    : 34
source     :
    - git|https://github.com/solus-project/budgie-desktop-branding.git : 3538484b5def9b4f6b77659b74f7956f62f0f4d3
license    : GPL-2.0
summary    :
    - Budgie Desktop Experience Configuration
    - material : Material design inspired Budgie Desktop experience
component  : desktop.budgie
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
        - /usr/share/lightdm
    - material :
        - /usr/share/glib-2.0/schemas/20_budgie_material_settings.gschema.override
        - /usr/share/lightdm/lightdm-gtk-greeter.conf.d/20_budgie_material.conf
        - /usr/share/budgie-desktop/layouts/solus-material.layout
rundeps    :
    - breeze-cursor-theme
    - font-clear-sans-ttf
    - qtstyleplugins
    - solus-artwork
    - material :
        - budgie-desktop-branding
        - adapta-gtk-theme
        - papirus-icon-theme
        - noto-sans-ttf
        - font-roboto-ttf
description: |
    Defaults for the Budgie Desktop
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
