name       : budgie-desktop-branding
version    : 3
release    : 6
source     :
    - https://github.com/solus-project/budgie-desktop-branding/releases/download/v3/budgie-desktop-branding-3.tar.xz : 5f72b09d3b5707b467b5f990406edcb7e836fca3e064982fb87dd3dc7738352c
license    : GPL-2.0
summary    : Budgie Desktop Experience Configuration
component  : desktop.budgie
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
rundeps    :
    - solus-artwork
    - breeze-snow-cursor-theme
    - font-clear-sans-ttf
    - arc-gtk-theme
    - faba-icon-theme-mono
    - arc-icon-theme
description: |
    Defaults for the Budgie Desktop
setup      : |
    %patch -p1 < $pkgfiles/0001-Added-some-launchers.patch
    %patch -p1 < $pkgfiles/0002-Match-the-pin-launcher-icon-to-the-new-installer-GTK.patch
    %patch -p1 < $pkgfiles/0003-Don-t-use-SC-icon-on-the-LiveCD.-I-mean-USB.-Nobody-.patch
    %configure
build      : |
    %make
install    : |
    %make_install
