name       : budgie-desktop-branding
version    : 6
release    : 14
source     :
    - https://github.com/solus-project/budgie-desktop-branding/releases/download/v6/budgie-desktop-branding-6.tar.xz : 81c498f0c5cd1def7a2fd8249928bb0db4aec71d6f70af546e9b871c75ffd7f4
license    : GPL-2.0
summary    : Budgie Desktop Experience Configuration
component  : desktop.budgie
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
        - /usr/share/lightdm
rundeps    :
    - solus-artwork
    - breeze-cursor-theme
    - font-clear-sans-ttf
    - arc-gtk-theme
    - faba-icon-theme-mono
    - arc-icon-theme
description: |
    Defaults for the Budgie Desktop
setup      : |
    %apply_patches
    %reconfigure
build      : |
    %make
install    : |
    %make_install
