name       : budgie-desktop-branding
version    : '11'
release    : 24
source     :
    - https://github.com/solus-project/budgie-desktop-branding/releases/download/v11/budgie-desktop-branding-11.tar.xz : fa074feea200a1360cd19d2eb4e1d579e6a1c50c4bb028b62fa439afc899ee2c
license    : GPL-2.0
summary    :
    - Budgie Desktop Experience Configuration
    - material: Material design inspired Budgie Desktop experience
component  : desktop.budgie
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
        - /usr/share/lightdm
    - material:
        - /usr/share/glib-2.0/schemas/20_budgie_material_settings.gschema.override
        - /usr/share/lightdm/lightdm-gtk-greeter.conf.d/20_budgie_material.conf
rundeps    :
    - arc-gtk-theme
    - arc-icon-theme
    - breeze-cursor-theme
    - faba-icon-theme-mono
    - font-clear-sans-ttf
    - qtstyleplugins
    - solus-artwork
    - material:
        - budgie-desktop-branding
        - adapta-gtk-theme
        - papirus-icon-theme
description: |
    Defaults for the Budgie Desktop
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
