name       : budgie-desktop-branding
version    : '12'
release    : 26
source     :
    - https://github.com/solus-project/budgie-desktop-branding/releases/download/v12/budgie-desktop-branding-12.tar.xz : 5a6fe0d8ea7ded4beab3b037ed8af1a19b9811917e8764ed783c7cb8d58ef7a9
license    : GPL-2.0
summary    :
    - Budgie Desktop Experience Configuration
    - material : Material design inspired Budgie Desktop experience
component  : desktop.budgie
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
        - /usr/share/lightdm
    - material :
        - /usr/share/glib-2.0/schemas/20_budgie_material_settings.gschema.override
        - /usr/share/lightdm/lightdm-gtk-greeter.conf.d/20_budgie_material.conf
rundeps    :
    - arc-gtk-theme
    - arc-icon-theme
    - breeze-cursor-theme
    - faba-icon-theme-mono
    - font-clear-sans-ttf
    - qtstyleplugins
    - solus-artwork
    - material :
        - budgie-desktop-branding
        - adapta-gtk-theme
        - papirus-icon-theme
description: |
    Defaults for the Budgie Desktop
setup      : |
    %patch -p1 < $pkgfiles/0001-schemas-Don-t-pin-installer-anymore.patch
    %reconfigure
build      : |
    %make
install    : |
    %make_install
