name       : budgie-desktop-branding
version    : 2
release    : 1
source     :
    - https://github.com/solus-project/budgie-desktop-branding/releases/download/v2/budgie-desktop-branding-2.tar.xz : 1045c70c90783010a108772389e195d860f349d098294ce1de6518dde3ae3b14
license    : GPL-2.0
summary    : Budgie Desktop Experience Configuration
component  : desktop.budgie
patterns   :
    - livecd:
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
rundeps    :
    - budgie-desktop
    - solus-artwork
    - breeze-snow-cursor-theme
    - font-clear-sans-ttf
    - arc-gtk-theme
    - faba-icon-theme-mono
description: |
    Defaults for the Budgie Desktop
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
