name       : budgie-desktop-branding
version    : '21.2'
release    : 64
source     :
    - git|https://dev.getsol.us/source/budgie-desktop-branding-src.git : 5331cabec4445e8e6df8ab445e49b7de3a5c2678
license    : GPL-2.0-only
summary    :
    - Budgie Desktop Experience Configuration
    - fortitude : Primary Solus 4 Fortitude defaults for the Budgie Desktop experience
    - fortitude-plus : Solus 4.2 and higher defaults.
    - livecd : Budgie LiveCD-specific Configuration
    - material : Material design inspired Budgie Desktop experience
description:
    - Defaults for the Budgie Desktop
    - fortitude : Primary Solus 4 series Fortitude defaults for the Budgie Desktop experience
    - fortitude-plus : Solus 4.2 and higher defaults.
    - livecd : Budgie LiveCD-specific Configuration
    - material : Material design inspired Budgie Desktop experience
component  :
    - desktop.budgie
    - fortitude : desktop.budgie
    - fortitude-plus : desktop.budgie
    - livecd : desktop.budgie
    - material : desktop.budgie
patterns   :
    - fortitude :
        - /usr/share/budgie-desktop/layouts/solus-fortitude.layout
        - /usr/share/glib-2.0/schemas/30_budgie_settings.gschema.override
        - /usr/share/lightdm/lightdm-gtk-greeter.conf.d/30_budgie_fortitude.conf
    - fortitude-plus :
        - /usr/share/glib-2.0/schemas/40_budgie_settings.gschema.override
        - /usr/share/lightdm/lightdm-gtk-greeter.conf.d/40_budgie_fortitude.conf
    - livecd :
        - /usr/share/glib-2.0/schemas/50_budgie_settings.gschema.override
        - /usr/share/lightdm/lightdm.conf.d/budgie_config.conf
    - material :
        - /usr/share/budgie-desktop/layouts/solus-material.layout
        - /usr/share/glib-2.0/schemas/20_budgie_settings.gschema.override
        - /usr/share/lightdm/lightdm-gtk-greeter.conf.d/20_budgie_material.conf
rundeps    :
    - breeze-cursor-theme
    - budgie-desktop
    - font-clear-sans-ttf
    - qtstyleplugins
    - solus-artwork
    - fortitude :
        - budgie-desktop-branding
        - font-roboto-ttf
        - noto-sans-ttf
        - papirus-icon-theme
        - materia-gtk-theme
        - materia-gtk-theme-dark
    - fortitude-plus :
        - budgie-desktop-branding-fortitude
    - material :
        - adapta-gtk-theme
        - budgie-desktop-branding
        - font-roboto-ttf
        - noto-sans-ttf
        - papirus-icon-theme
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
