name       : budgie-desktop-branding
version    : '20.1'
release    : 42
source     :
    - git|https://dev.getsol.us/source/budgie-desktop-branding-src.git : a1cbdf9bcb85a08445ff7506161d224d5217ea9c
license    : GPL-2.0-only
summary    :
    - Budgie Desktop Experience Configuration
    - fortitude : Solus 4.0 Fortitude defaults for the Budgie Desktop experience
    - livecd : Budgie LiveCD-specific Configuration
    - material : Material design inspired Budgie Desktop experience
description:
    - Defaults for the Budgie Desktop
    - fortitude : Solus 4.0 Fortitude defaults for the Budgie Desktop experience
    - livecd : Budgie LiveCD-specific Configuration
    - material : Material design inspired Budgie Desktop experience
component  :
    - desktop.budgie
    - fortitude : desktop.budgie
    - livecd : desktop.budgie
    - material : desktop.budgie
patterns   :
    - fortitude :
        - /usr/share/budgie-desktop/layouts/solus-fortitude.layout
        - /usr/share/glib-2.0/schemas/30_budgie_settings.gschema.override
        - /usr/share/lightdm/lightdm-gtk-greeter.conf.d/30_budgie_fortitude.conf
    - livecd :
        - /usr/share/glib-2.0/schemas/40_budgie_settings.gschema.override
        - /usr/share/lightdm/lightdm.conf.d/budgie_config.conf
    - material :
        - /usr/share/budgie-desktop/layouts/solus-material.layout
        - /usr/share/glib-2.0/schemas/20_budgie_settings.gschema.override
        - /usr/share/lightdm/lightdm-gtk-greeter.conf.d/20_budgie_material.conf
rundeps    :
    - breeze-cursor-theme
    - budgie-desktop
    - font-clear-sans-ttf
    - qtstyleplugins
    - solus-artwork
    - fortitude :
        - budgie-desktop-branding
        - font-roboto-ttf
        - noto-sans-ttf
        - papirus-icon-theme
        - plata-theme
    - material :
        - adapta-gtk-theme
        - budgie-desktop-branding
        - font-roboto-ttf
        - noto-sans-ttf
        - papirus-icon-theme
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
