name       : budgie-desktop-branding
version    : '17'
release    : 35
source     :
    - git|https://github.com/solus-project/budgie-desktop-branding.git : f5fd730e0a27bc8196733486cb47373aa1883e80
license    : GPL-2.0-only
summary    :
    - Budgie Desktop Experience Configuration
    - material : Material design inspired Budgie Desktop experience
component  : desktop.budgie
patterns   :
    - livecd :
        - /usr/share/glib-2.0/schemas/*livecd.gschema.override
        - /usr/share/lightdm
    - material :
        - /usr/share/glib-2.0/schemas/20_budgie_material_settings.gschema.override
        - /usr/share/lightdm/lightdm-gtk-greeter.conf.d/20_budgie_material.conf
        - /usr/share/budgie-desktop/layouts/solus-material.layout
rundeps    :
    - breeze-cursor-theme
    - font-clear-sans-ttf
    - qtstyleplugins
    - solus-artwork
    - material :
        - budgie-desktop-branding
        - adapta-gtk-theme
        - papirus-icon-theme
        - noto-sans-ttf
        - font-roboto-ttf
description: |
    Defaults for the Budgie Desktop
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
